### ISSUE TITLE
Serialization crash

### ISSUE THREAD

**Issue by ravimohan1991** [ravimohan1991/ChatDiamond#14] opened 2023-05-26 03:35 UTC
At least one instance exists where serialization causes native code to crash.

![image](https://github.com/ravimohan1991/ChatDiamond/assets/2173654/1fa6ec21-157f-4e6b-867a-3da3dd211ace)

also an accessed none warning on the sides
![image](https://github.com/ravimohan1991/ChatDiamond/assets/2173654/82c7ef0b-03a4-43c5-b8e8-04877833a8d3)

**Comment by ravimohan1991** [comment] 2023-05-31 23:15
Another error
![image](https://github.com/ravimohan1991/ChatDiamond/assets/2173654/d70a0836-2fad-4214-86b5-aa20a108460c)

**Comment by ravimohan1991** [comment] 2023-06-03 00:39
The issue seems to be fixed.

**Comment by ravimohan1991** [comment] 2023-06-14 12:18
Another instance of crash, no clue what is causing
```
Critical: ACDDiscordActor::execSerializeJson
Critical: RemoteCall
Critical: HandleStream
Critical: UActorChannel::ReceivedBunch
Critical: (Actor TMale10)
Critical: UChannel::ReceivedSequencedBunch
Critical: Direct
Critical: UChannel::ReceivedRawBunch
Critical: DispatchDataToChannel
Critical: BunchData
Critical: UNetConnection::ReceivedPacket
Critical: UNetConnection::ReceivedRawPacket
Critical: UTcpNetDriver::TickDispatch
Critical: UpdatePreNet
Critical: ULevel::Tick
Critical: (NetMode=3)
Critical: TickLevel
Critical: UGameEngine::Tick
Critical: ACE1
Critical: EnforceTickRate
Critical: MainLoop
```

**Comment by ravimohan1991** [comment] 2023-06-16 10:58
```
Critical: ACDDiscordActor::execSerializeJson
Critical: RemoteCall
Critical: HandleStream
Critical: UActorChannel::ReceivedBunch
Critical: (Actor CHSpectator0)
Critical: UChannel::ReceivedSequencedBunch
Critical: Direct
Critical: UChannel::ReceivedRawBunch
Critical: DispatchDataToChannel
Critical: BunchData
Critical: UNetConnection::ReceivedPacket
Critical: UNetConnection::ReceivedRawPacket
Critical: UTcpNetDriver::TickDispatch
Critical: UpdatePreNet
Critical: ULevel::Tick
Critical: (NetMode=3)
Critical: TickLevel
Critical: UGameEngine::Tick
Critical: ACE1
Critical: EnforceTickRate
Critical: MainLoop
```

**Comment by ravimohan1991** [comment] 2023-06-23 12:59
Maybe related crashes
https://github.com/nlohmann/json/issues/1365
https://github.com/nlohmann/json/issues/2126

To set utf-8 in msvc
https://learn.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170

**Comment by ravimohan1991** [comment] 2023-06-23 16:03
Ok tried catching the exception throwing snippet (commit [6b564bcb](https://github.com/ravimohan1991/ChatDiamond/commit/6b564bcb01de817db6665ae9a65bcc6e5b93761b)). Caught the following
```
Search "[Chat Diamond] exception" (26 hits in 1 file of 1 searched)
  G:\SteamLibrary\UnrealTournamentGOTY\System\UnrealTournament.log (26 hits)
	Line  408: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7尶
	Line  409: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7ㆀꏚ줩Ѐ褂䠘䩈is brutalizing the competition!
	Line  410: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7ㅦ
	Line  579: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7㉣
	Line  857: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7
	Line 1836: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7戁⛩⬲�⡸踀མ䫤䐄氶ꇝᩊ찀ꇨŊ場䬭଄DownUnder.NDgencli0
	Line 2147: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7
	Line 2150: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7鑙邱�ⵐ耀퍐䩹Engine.PlayerPawn.TeamMessage.
	Line 2151: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7
	Line 2152: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7
	Line 2153: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7AdȪ탭ᑳ耀䞘⏅Friday 23 Jun 2023 19:15
	Line 2154: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7଄嚞�븀耀䩇Engine.PlayerPawn.TeamMessage.
	Line 2155: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7璵ⶔ捂펣嬀輀䳘⍾The_Men0rA entered the game.
	Line 2156: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7
	Line 2157: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7逹쒆쬃팘ɀ耀໠㫃Engine.PlayerPawn.TeamMessage.
	Line 2158: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7
	Line 2159: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7
	Line 2881: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7
	Line 2989: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7
	Line 3055: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7
	Line 3102: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7ㅦ
	Line 3111: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7
	Line 3146: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7
	Line 3157: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7�ꨘ퍿ఀ謀㫂鞑
	Line 3174: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7
	Line 3216: Log: [Chat Diamond] exception 橛潳⹮硥散瑰潩⹮祴数敟牲牯㌮㘱⁝湩慶楬⁤呕ⵆ‸祢整愠⁴湩敤⁸㨵〠䉸7
```

**Comment by garry-ut99** [comment] 2023-08-13 16:28
Same ~~shit~~ for me, getting crashes every 2nd game, since I've installed beta version of ChatDiamond today : [LINK](https://eatsleeput.com/d/192-chatdiamond/67), I played several games today and have gotten 4 crashes so far (2 different messages), in different maps, and just like in:
- https://github.com/OldUnreal/UnrealTournamentPatches/issues/1260

they've appeared during  switching levels on the server, thus I don't know whether it's related to the previous crashes and caused by bugged ACE and already fixed in ACE 1.3, or a different bug caused by bugged ChatDiamond, hence I have posted on UT99 469 patch repo too:
- https://github.com/OldUnreal/UnrealTournamentPatches/issues/1347

2 times
![crash](https://github.com/OldUnreal/UnrealTournamentPatches/assets/72945564/899ac1cb-5b9a-42fe-be8e-b48f36c83d31)

2 times
![crash2](https://github.com/OldUnreal/UnrealTournamentPatches/assets/72945564/a379083b-3c9e-473b-b322-e7749e7277cb)

**Comment by ravimohan1991** [comment] 2023-08-14 04:04
Thanks for the feedback. Please note that the harsh language that you have used is unpleasant and will not be accepted here. Please refer to https://github.com/ravimohan1991/ChatDiamond/blob/main/CODE_OF_CONDUCT.md for the information on how to be graceful to yourself and people around you.

**Comment by garry-ut99** [comment] 2023-08-14 09:38
Don't cry boy, clowns like you, who lecture others about morality, when they themselves accept its non-observance, are so funny: [LINK](https://eatsleeput.com/d/192-chatdiamond/75).

**Closed as completed** 2023-11-22 13:00 UTC
Labels: bug
